version: '3'

services:

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    command: npm run start
    volumes:
      - .:/usr/src/app

  pg:
    image: postgres:16.0-alpine3.18
    restart: unless-stopped
    ports: 
      - ${PG_PORT}:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
    depends_on:
      - pg

  #ws:
  #  build:
  #    context: ../ws_checkers
  #    dockerfile: ./Dockerfile
  #  restart: unless-stopped
  #  environment:
  #    WS_PORT: ${WS_PORT:-8081}  # TODO actually use the WS_PORT in the dockerfile


