version: '3'

services:

  web:
    image: luc527/node_checkers@latest
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:80
    command: npm run start
    volumes:
      - .:/usr/src/app

  pg:
    image: postgres:16.0-alpine3.18
    restart: unless-stopped
    ports: 
      - ${PG_PORT}:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
    depends_on:
      - pg

  ws:
    image: luc527/ws_checkers@latest
    restart: unless-stopped
    ports:
      - ${WS_PORT}:88
    environment:
      DB_PATH: "/go/bin/checkers.db"


