name: 'Push to testing environment'

on:
  push:
    branches:
      - development

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub login
        run: echo 'Logging into Docker Hub'

      - name: Build Docker image
        run: echo 'Building image luc527/ese_web_checkers'
          - echo 'Pushing image to Docker Hub'

      - name: Push Docker image to Docker hub
        run: echo 'Pushing image to Docker Hub'

      - name: Deploy to QA environment
        run: cat compose/qa/docker-compose.yml

